version: '3.1'
services:
  frontend:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - 8081:80
    environment:
      - ENV_DOCKER_REGISTRY_HOST=10.0.4.9
      - ENV_DOCKER_REGISTRY_PORT=5000

  registry:
    image: registry:2
    restart: always
    container_name: registry
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=./auth/htpasswd
    ports:
      - 5000:5000
    volumes:
      - ./data:/var/lib/registry
      - ./auth:/auth
